## Netlify configuration file for GBTS Builders Solution Ltd project
## https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run generate"            # Nuxt static site generation
  functions = "netlify/functions"         # Serverless functions directory (if any)
  publish = "dist"                        # Output directory for generated static files

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
